### ISSUE TITLE
Comparision with TinyGo?

### ISSUE THREAD

**Issue by prologic** [inversepath/tamago#1]
How does this project compare with that of [TinyGo](https://github.com/tinygo-org/tinygo)? Could the `tamago` target be merged with / ported to TinyGo where they have a much larger range of supported hardware platforms that Go code can be compiled to?

**Comment by andrejro** [comment]
Hi, please check:

https://github.com/inversepath/tamago/wiki/Frequently-Asked-Questions-(FAQ)#how-does-tamago-differ-from-tinygo

Thanks
